apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: martech-prod
commonLabels:
  environment: production
resources:
- ingress-api.yaml
- ingress-dash.yaml
- ../../base
images:
- name: bert-email-router
  newName: docker.pkg.github.com/nuuday/bert_email_router/bert_email_router
  newTag: v0.1.23-cpu
