apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert-email-router-api
  labels:
    app: bert-email-router-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bert-email-router-api
  template:
    metadata:
      labels:
        app: bert-email-router-api
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: dataai-mlflow
      securityContext:
        fsGroup: 65534
      containers:
      - name: bert-email-router-api
        image: bert-email-router
        ports:
        - containerPort: 8000
        env:
          - name: MARIADB_USR
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: MARIADB_USR
          - name: MARIADB_PSW
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: MARIADB_PSW
          - name: AWS_DEFAULT_REGION
            value: eu-central-1
          - name: MLFLOW_S3_ENDPOINT_URL
            value: https://s3.eu-central-1.amazonaws.com/
          - name: MLFLOW_S3_UPLOAD_EXTRA_ARGS
            value: '{"ACL": "bucket-owner-full-control"}'
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: mlflow
                key: MLFLOW_TRACKING_USERNAME
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow
                key: MLFLOW_TRACKING_PASSWORD
        resources:
          limits:
            memory: 2048Mi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.2"
        command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
      imagePullSecrets:
      - name: gh-docker-creds